services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employees
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  nestjs:
    build:
      dockerfile: Dockerfile
    container_name: api-nestjs
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    networks:
      - app-network

  react:
    build:
      dockerfile: Dockerfile
    container_name: front-react
    ports:
     - "3000:3000"

volumes:
  postgres_data:

networks:
  app-network: